accounts/urls.py
from django.urls import path, include 
from django.contrib.auth.views import PasswordResetDoneView
from accounts.views import UserLogin, UserCreate, UserChange, PasswordChange, PasswordReset, PasswordResetConfirm, PasswordResetComplete, UserDelete, TimeOutView 


app_name = "accounts"
urlpatterns = [
	path('login/', UserLogin.as_view(), name='login'),
	path('user-new/', UserCreate.as_view(), name='user-new'), 
	path('<int:pk>/update/', UserChange.as_view(), name='user-change'), 
	path('password-change/', PasswordChange.as_view(), name='password-change'),
        path('<int:pk>/delete/', UserDelete.as_view(), name='user-delete'),
	path('password-reset/', PasswordReset.as_view(), name='password-reset'),
	path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name="password_reset_confirm"),
	path('reset/done/', PasswordResetComplete.as_view(), name='password_reset_complete'),
	path('', include('django.contrib.auth.urls')), 
	path('timeout/', TimeOutView.as_view(), name='timeout'),
]
 

home/urls.py
from django.urls import path
from home.views import (CategoryFilterView, HomeView, DetailView, TagIndexView)
from home.likes_comments import (AddDislike, AddLike, CommentDeleteView, CommentEditView, CommentReplyView, AddCommentDislike, AddCommentLike) 

app_name = "home"
urlpatterns = [
        path('', HomeView.as_view(), name='home'),
        path('post-detail/<int:pk>/', DetailView.as_view(), name='post-detail'),
        path('tags/<slug:tag_slug>/', TagIndexView.as_view(), name='tagged'),
        path('category/<int:cat_slug>/', CategoryFilterView.as_view(), name='category'),
        path('post/<int:pk>/like', AddLike.as_view(), name='like'),
        path('post/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
        path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name="comment-delete"),
        path('post/<int:post_pk>/comment/edit/<int:pk>/', CommentEditView.as_view(), name="comment-edit"),
        path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name="comment-like"),
        path('post/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name="comment-dislike"),
        path('post/<int:post_pk>/comment/<int:pk>/reply', CommentReplyView.as_view(), name='comment-reply'),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('profile/', include('profile.urls')),
    path('post/', include('post.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path
from profile.views import ProfileAddLike, EditPhotoProfile, ProfileView, ProfileEditView, UserListView, UserCreateView, ConfigView

app_name = "profile"
urlpatterns = [
    path('config/', ConfigView.as_view(), name="config"),
    path('edit-profile', ProfileEditView.as_view(), name="edit-profile"),
    path('<slug:username>', ProfileView.as_view(), name="user-profile"),
    path('profile/<int:pk>/like', ProfileAddLike.as_view(), name='like-profile'),
    path('<int:pk>/photo/', EditPhotoProfile.as_view(), name='photo-profile'),
    path('usuarios/', UserListView.as_view(), name='users-profile'),
    path('usernew/', UserCreateView.as_view(), name='usernew'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core import validators
from django.utils.translation import ugettext_lazy as _
import re


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError('Email is mandatory')

        email = self.normalize_email(email)
        user = self.model(email=email, username=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        print("usermanager")
        return user

    def create_user(self, email, password=None, **extra_fields):

        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):

        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser need to be is_superuser=True')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser need to be is_staff=True')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):

    TYPE_USER_CHOICES = [('ad', 'Administrator'),
                         ('co', 'Collaborator'), ('us', 'Default User')]
    user_name = models.CharField(_('user_name'), max_length=15, unique=True, help_text=_('Required. 15 characters or fewer. Letters, numbers and @/./+/-/_ characters'),
                                 validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'), _('Enter a valid username.'), _('invalid'))])
    email = models.EmailField('Email', unique=True)
    type_user = models.CharField(
        'type_user', max_length=2, choices=TYPE_USER_CHOICES)
    is_staff = models.BooleanField('Team member', default=True)
    is_active = models.BooleanField('active', default=False)
    date_joined = models.DateTimeField('date joined', auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['user_name', 'first_name',
                       'last_name', 'type_user', 'is_active']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['first_name']

    def __str__(self):
        return self.email

    objects = UserManager()

profile/models.py
from re import M
from django.db.models.signals import post_save
from django.dispatch import receiver 
from django.db import models 
from stdimage.models import StdImageField    
from accounts.models import CustomUser 


class SocialNetwork(models.TextChoices):
        YOUTUBE = 'youtube', 'youtube'
        WHATSAPP = 'whatsapp', 'whatsapp'
        FACEBOOK = 'facebook', 'facebook'
        INSTAGRAM = 'instagram', 'instagram'
        TWITTER = 'twitter', 'twitter'
        PINTEREST = 'pinterest', 'pinterest'
        SNAPCHAT = 'snapchat', 'snapchat'
        TIKTOK = 'tiktok', 'tiktok'
        DISCORD = 'discord', 'discord'
        GITHUB = 'github', 'github'
 
class Profile(models.Model):   
        user = models.OneToOneField(CustomUser,  on_delete=models.CASCADE, related_name='profile') 
        image = StdImageField('Image', upload_to='profile', variations={'thumb': (500, 500, True)}, delete_orphans = True, blank=True)  
        occupation = models.CharField(max_length=120)
        description = models.TextField()  
        gender = models.CharField(max_length=20, blank=True)
        phone = models.CharField(max_length=20, blank=True)
        city = models.CharField(max_length=20, blank=True)
        country = models.CharField(max_length=20, blank=True)
        likes = models.ManyToManyField(CustomUser, blank=True, related_name='profile_likes')

        def __str__(self):
                return f' Profile: {self.user.username}'

        class Meta:
                verbose_name = "Profile"
                verbose_name_plural = "Profiles"
        
        @receiver(post_save, sender=CustomUser)
        def create_profile(sender, **kwargs):
                if kwargs.get('created', False):
                        Profile.objects.create(user=kwargs['instance'])

class Network(models.Model):
        user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='network', blank=True, null=True)  
        name = models.CharField(max_length=10, choices=SocialNetwork.choices, blank=True, null=True) 
        url = models.URLField(blank=True, null=True)

        def __str__(self):
                return f'{self.user or ""}, {self.name}'
        
        class Meta:
                verbose_name = "Network"
                verbose_name_plural = "Networks"
                ordering = ['user']

        @receiver(post_save, sender=CustomUser)
        def create_network(sender, **kwargs):  
                if kwargs.get('created', False):    
                        for i in SocialNetwork:
                                print(i)
                                Network.objects.create(name=i, user=kwargs['instance']) 
         
                                
                                

       

profile/forms.py
from django import forms
from profile.models import Network, Profile


class NetworkForm(forms.ModelForm):
    class Meta:
        model = Network
        fields = '__all__'


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

profile/views.py
import re
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic.base import View
from django.views.generic.edit import CreateView
from accounts.forms import CustomUserCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from base.base_admin_permissions import BaseAdminUsersAd
from django.views.generic import TemplateView, DetailView, UpdateView, ListView
from profile.models import Network, Profile
from rest_framework import viewsets
from accounts.models import CustomUser
from post.models import Post


class ProfileView(DetailView):
    model = CustomUser
    template_name = "profile/profile.html"
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "profile"
    object = None

    def get_object(self, queryset=None):
        self.profile = self.model.objects.select_related('profile').prefetch_related(
            "posts").prefetch_related("network").get(user_name=self.kwargs.get(self.slug_url_kwarg))
        return self.profile

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        page = self.request.GET.get('page')
        title = request.GET.get('title')
        if title:
            context['page_obj'] = Paginator(Post.objects.all().filter(
                title__icontains=title, author=self.object, is_activate__exact=True), 6).get_page(page)
            print("resultado filtro !!!")
            print(context['page_obj'])
        else:
            context['page_obj'] = Paginator(Post.objects.all().filter(
                author=self.object, is_activate__exact=True), 6).get_page(page)
            print("Todos os filtros !!!")
        return self.render_to_response(context)


class ProfileEditView(UpdateView):
    model = Profile
    template_name = "config/edit-profile.html"
    context_object_name = "profile"
    object = None
    fields = "__all__"

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['network'] = Network.objects.filter(user=self.request.user)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        print(request.POST.get('first_name'))
        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.save()
        profile = user.profile
        profile.about = request.POST.get('about')
        profile.occupation = request.POST.get('occupation')
        profile.description = request.POST.get('description')
        if request.POST.get('gender') == "Homem":
            profile.gender = "Homem"
        else:
            profile.gender = "Mulher"
        profile.country = request.POST.get('country')
        profile.city = request.POST.get('city')
        profile.phone = request.POST.get('phone')
        profile.save()
        # Ele junta duas listas, de preferencia do mesmo tamanho.
        networks = Network.objects.filter(user=self.request.user)
        urls = request.POST.getlist('url')
        for network, url in zip(networks, urls):
            network.url = url
            network.save()
        messages.success(self.request, 'Alterações salva com sucesso!!!')
        return redirect(reverse_lazy('profile:edit-profile'))


class EditPhotoProfile(UpdateView):
    model = Profile
    template_name = "profile/profile.html"
    template_name_suffix = '_update_form'
    fields = ['image']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(
            self.request, 'Imagem de profile atualizada com sucesso!!!')
        return reverse_lazy('profile:user-profile', args=[self.request.user.user_name])


class ProfileAddLike(LoginRequiredMixin, View):
    slug_field = "username"
    slug_url_kwarg = "username"

    def post(self, request, pk, *args, **kwargs):
        profile = Profile.objects.get(pk=pk)
        is_like = False
        for like in profile.likes.all():
            if like == request.user:
                is_like = True
                break
        if not is_like:
            profile.likes.add(request.user)

        if is_like:
            profile.likes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)


class ConfigView(TemplateView):
    template_name = "config/_config.html"


class UserListView(BaseAdminUsersAd, ListView):
    model = Profile
    template_name = 'config/usuarios.html'
    context_object_name = 'profile_list'

    def get_queryset(self):
        user_name = self.request.GET.get('user_name')
        is_active = self.request.GET.get('is_active')

        if user_name:
            profile_list = Profile.objects.filter(
                user__user_name__icontains=user_name)
            return profile_list
        if is_active:
            profile_list = Profile.objects.filter(user__is_active=is_active)
            return profile_list
        else:
            profile_list = Profile.objects.filter()
        return profile_list


class UserCreateView(CreateView):
    model = CustomUser
    form_class = CustomUserCreateForm
    template_name = 'config/add-user.html'
    success_url = reverse_lazy('profile:users-profile')

profile/templates/config/_config.html
{% extends 'base/_base_home.html' %} {% load widget_tweaks %} {% load static %}
{% block body_home %}
<div class="row">
  <div class="container-box col-md-3 p-3 bg-light">
    <h5>Settings</h5>
    <div class="col mb-2 py-1">
      <a href="{%  url 'post' %}"
        ><button class="btn-default btn-red" type="button">
          My questions
        </button></a
      >
    </div>
    <div class="col mb-2 py-1">
      <a href="{%  url 'accounts:user-change' user.pk %}"
        ><button class="btn-default btn-red" type="button">
          My account
        </button></a
      >
    </div>
    <div class="col mb-2 py-1">
      <a onclick="location.href='http://127.0.0.1:8000/profile/edit-profile'"
        ><button class="btn-default btn-red" type="button">
          Update Profile
        </button></a
      >
    </div>
    {% if user.is_superuser %}
    <hr />
    <div class="col mb-2 py-1">
      <a href="{%  url 'profile:users-profile' %}"
        ><button class="btn-default btn-red" type="button">All Users</button></a
      >
    </div>
    <div class="col mb-2 py-1">
      <a href="{%  url 'post-todos' %}"
        ><button class="btn-default btn-red" type="button">
          All Questions
        </button></a
      >
    </div>
    {% endif %}
  </div>
  <div class="col-md-9">
    {% block config %}
    <div class="container-box lead">
      <h2>
        <span class="link-success"
          ><i class="fas fa-arrow-left fa-3x"></i
        ></span>
        Select an item from the menu
      </h2>
    </div>
    {% endblock %}
  </div>
</div>
{% endblock %}

profile/templates/config/add-user.html
{% extends 'config/_config.html' %}
{% block title %}Add User{% endblock %}
{% load static %}
{% block config %} 
<form class="container-box lead" method="POST" action="{% url 'profile:usernew' %}" enctype="multipart/form-data" autocomplete="off">
        {% csrf_token %}
        <h2>Register New User</h2>
        <div class="row">
                <div class="col-sm-6 mt-3">
                        <label for="username">Email<span style="color: red;">*</span></label>
                        <input type="email" class="form-control" id="username" name="username" required autofocus>
                </div>
                <div class="col-sm-6 mt-3">
                        <label for="user_name"><b>Username</b><span style="color: red;">*</span></label>
                        <input type="text" class="form-control" id="user_name" name="user_name" required autofocus>
                        <span id="password-help" class="text-muted">Your username must contain a maximum of 8 characters.</span><br>
                </div>
        </div>
        <div class="row">
                <div class="col-sm-6 mt-3">
                        <label for="first_name">First Name<span style="color: red;">*</span></label>
                        <input type="text" class="form-control" id="first_name" name="first_name" required>
                </div>
                <div class="col-sm-6 mt-3">
                        <label for="last_name">Last Name<span style="color: red;">*</span></label>
                        <input type="text" class="form-control" id="last_name" name="last_name" required> 
                </div>
        </div>
        <div class="col-sm-6 mt-3">
                <label for="type_user">User Type<span style="color: red;">*</span></label>
                <select class="form-select form-control" id="type_user" name="type_user" selected>
                        {% for i in form.type_user %}
                        {{i}}
                        {% endfor %}
                </select>
        </div>
        <br>
        <div class="row">
                <div class="col-sm-6">
                        <div class="mt-3">
                                <label for="password1">password<span style="color: red;">*</span></label>
                                <input type="password" class="form-control" id="password1" name="password1" required>
                                <span id="password-help" class="text-muted">Your password must contain at least 8 characters. And at least 1 number and 1 capital letter.</span>
                        </div>
                </div>
                <div class="col-sm-6">
                        <div class= mt-3">
                                <label for="password2">Confirmação da password<span style="color: red;">*</span></label>
                                <input type="password" class="form-control" id="password2" name="password2" required>
                        </div>
                </div>
        </div>
        <div class="mt-3">
                <button type="submit" class="btn-default btn-red">Cadastrar</button> 
        </div>
</form>  
{% endblock %}

profile/templates/config/edit-profile.html
{% extends 'config/_config.html' %} {% load widget_tweaks %} {% load static %}
{% block config %}
<form
  class="container-box lead"
  method="post"
  action="{% url 'profile:edit-profile' %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="row">
    <h3>Configurações</h3>
    <div class="col-md-6 mb-3">
      <label for="input">First Name</label>
      <input
        type="text"
        id="input"
        name="first_name"
        class="form-control"
        required="required"
        value="{{ request.user.first_name }}"
      />
    </div>
    <div class="col-md-6 mb-3">
      <label for="input">Last Name</label>
      <input
        type="text"
        name="last_name"
        class="form-control"
        required="required"
        value="{{ request.user.last_name }}"
      />
    </div>
  </div>
  <div class="row">
    <h3>About</h3>
    <div class="col-md-12 mb-3">
      <label for="textarea">About Me</label>
      <textarea
        rows="4"
        id="textarea"
        class="form-control"
        required="required"
        name="description"
      >
{{ profile.description }}</textarea
      >
    </div>
    <div class="col-md-6 mb-3">
      <label for="input">Country</label>
      <input
        type="text"
        name="country"
        class="form-control"
        required="required"
        value="{{ profile.country }}"
      />
    </div>
    <div class="col-md-6 mb-3">
      <label for="input">City</label>
      <input
        type="text"
        name="city"
        class="form-control"
        required="required"
        value="{{ profile.city }}"
      />
    </div>
    <div class="col-md-4 mb-3">
      <label for="input">occupation </label>
      <input
        type="text"
        name="occupation"
        class="form-control"
        required="required"
        value="{{ profile.occupation }}"
      />
    </div>
    <div class="col-md-4 mb-3">
      <br />
      <div class="form-check-inline">
        <label
          ><input type="radio" class="form-check-input" {% if profile.gender ==
          "Homem" %} checked="checked" {% endif %} name="gender" value="Homem">
          Homem</label
        >
      </div>
      <div class="form-check-inline">
        <label
          ><input type="radio" class="form-check-input" {% if profile.gender ==
          "Mulher" %} checked="checked" {% endif %} name="gender"
          value="Mulher"> Mulher</label
        >
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <label for="input">Telephone</label>
      <input
        type="text"
        name="phone"
        class="form-control"
        required="required"
        value="{{ profile.phone }}"
      />
    </div>
    <div class="col-md-12 mb-3">
      <div class="row mb-3">
        <h3>Social networks</h3>
        {% for n in network.all %}
        <label for="input" class="col-sm-2 col-form-label"
          >{{n.name|title}}</label
        >
        <div class="col-sm-10">
          <input
            type="text"
            name="url"
            id="url"
            class="form-control"
            value="{{n.url}}"
          />
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="mb-3">
    <button type="submit" class="btn-default btn-gray">Update</button>
    <button
      type="button"
      class="mr-2 btn-default btn-red"
      onclick="location.href='{% url 'profile:user-profile' request.user.user_name %}'"
    >
      Go back
    </button>
  </div>
</form>
{% endblock %}

profile/templates/config/usuarios.html
{% extends 'config/_config.html' %} {% block title %}List Users{% endblock %} {%
load static %} {% block config %}
<div class="row">
  <div class="col-auto">
    <button
      class="btn-default btn-red"
      onclick="location.href='{% url 'profile:usernew' %}'"
    >
      Novo Usuários
    </button>
  </div>
  <div class="col">
    <form
      class="row align-items-center"
      method="get"
      action="{% url 'profile:users-profile' %}"
    >
      <div class="col-auto form-check form-check-inline">
        <input type="radio" name="is_active" value="1" {% if
        request.GET.is_active == "1" %} checked="checked" {% endif %}>
        <label for="is_active">Activated</label>
      </div>
      <div class="col-auto form-check form-check-inline">
        <input type="radio" name="is_active" value="0" {% if
        request.GET.is_active == "0" %} checked="checked" {% endif %}>
        <label for="is_activate">Deactivated</label>
      </div>
      <div class="col-auto">
        <input
          name="user_name"
          type="text"
          value="{{request.GET.user_name}}"
          class="form-control"
          placeholder="Search by username..."
        />
      </div>
      <div class="col-auto">
        <button class="btn-default btn-red" type="submit">
          <i class="fa fa-search"></i>
        </button>
      </div>
    </form>
  </div>
  {% if request.GET.user_name or request.GET.is_active %}
  <div class="col-auto">
    <button
      class="btn-default btn-red"
      onclick="location.href='{% url 'profile:users-profile' %}'"
    >
      Reset
    </button>
  </div>
  {% endif %}
</div>
<div class="table-responsive">
  <table class="text-center table table-bordered rounded mt-3 shadow-sm">
    <thead class="table-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Photo</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">User Type</th>
        <th scope="col">Registration Date</th>
        <th scope="col">Active?</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    {% for user_list in profile_list %} {% if not user_list.is_superuser %}
    <tbody>
      <tr>
        <th scope="row">{{user_list.user.id}}</th>
        <th scope="row">
          {% if user_list.image %}
          <a
            data-bs-toggle="modal"
            href="#imgModal{{user_list.user.first_name}}"
          >
            <img
              src="{{user_list.image.thumb.url}}"
              class="img-fluid"
              alt="{{ user_list.first_name }}"
              width="30"
              height="30"
            />
          </a>
          {% else %}
          <img
            src="{% static 'images/default.png' %}"
            class="img-fluid"
            alt="{{ user_list.first_name }}"
            width="30"
            height="30"
          />
          {% endif %}
        </th>
        <th scope="row">
          {{user_list.user.first_name}} {{user_list.user.last_name}}
        </th>
        <th scope="row">{{user_list.user.username}}</th>
        <th scope="row">{{user_list.user.get_type_user_display}}</th>
        <th scope="row">{{user_list.user.date_joined}}</th>
        <th scope="row">
          {% if user_list.user.is_active %}
          <i class="link-success mx-2 fas fa-check-circle"></i>
          {% else %}
          <i class="link-light mx-2 fas fa-check-circle"></i>
          {% endif %}
        </th>
        <th scope="row">
          <a
            class="link-warning"
            href="{% url 'accounts:user-change' user_list.pk %}"
            ><i class="fas fa-eye"></i
          ></a>
          <a
            class="ml-2 link-secondary"
            href="{% url 'accounts:user-change' user_list.pk %}"
            ><i class="far fa-file"></i
          ></a>
          <a
            class="ml-3 link-danger"
            href="{% url 'accounts:user-delete' user_list.pk %}"
            ><i class="fas fa-trash"></i
          ></a>
        </th>
      </tr>
    </tbody>
    {% endif %}
    <div
      class="modal fade"
      id="imgModal{{user_list.user.first_name}}"
      tabindex="-1"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
              Profile photo of {{ user_list.user.first_name }}
            </h5>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body text-center">
            {% if user_list.image %}
            <img
              src="{{user_list.image.url}}"
              class="img-fluid"
              alt="{{ user_list.user.first_name }}"
            />
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </table>
</div>
{% endblock %}