home/urls.py
from django.urls import path
from home.views import (CategoryFilterView, HomeView, DetailView, TagIndexView)
from home.likes_comments import (AddDislike, AddLike, CommentDeleteView, CommentEditView, CommentReplyView, AddCommentDislike, AddCommentLike) 

app_name = "home"
urlpatterns = [
        path('', HomeView.as_view(), name='home'),
        path('post-detail/<int:pk>/', DetailView.as_view(), name='post-detail'),
        path('tags/<slug:tag_slug>/', TagIndexView.as_view(), name='tagged'),
        path('category/<int:cat_slug>/', CategoryFilterView.as_view(), name='category'),
        path('post/<int:pk>/like', AddLike.as_view(), name='like'),
        path('post/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
        path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name="comment-delete"),
        path('post/<int:post_pk>/comment/edit/<int:pk>/', CommentEditView.as_view(), name="comment-edit"),
        path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name="comment-like"),
        path('post/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name="comment-dislike"),
        path('post/<int:post_pk>/comment/<int:pk>/reply', CommentReplyView.as_view(), name='comment-reply'),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('profile/', include('profile.urls')),
    path('post/', include('post.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path
from profile.views import ProfileAddLike, EditPhotoProfile, ProfileView, ProfileEditView, UserListView, UserCreateView, ConfigView

app_name = "profile"
urlpatterns = [
    path('config/', ConfigView.as_view(), name="config"),
    path('edit-profile', ProfileEditView.as_view(), name="edit-profile"),
    path('<slug:username>', ProfileView.as_view(), name="user-profile"),
    path('profile/<int:pk>/like', ProfileAddLike.as_view(), name='like-profile'),
    path('<int:pk>/photo/', EditPhotoProfile.as_view(), name='photo-profile'),
    path('usuarios/', UserListView.as_view(), name='users-profile'),
    path('usernew/', UserCreateView.as_view(), name='usernew'),
]

profile/models.py
from re import M
from django.db.models.signals import post_save
from django.dispatch import receiver 
from django.db import models 
from stdimage.models import StdImageField    
from accounts.models import CustomUser 


class SocialNetwork(models.TextChoices):
        YOUTUBE = 'youtube', 'youtube'
        WHATSAPP = 'whatsapp', 'whatsapp'
        FACEBOOK = 'facebook', 'facebook'
        INSTAGRAM = 'instagram', 'instagram'
        TWITTER = 'twitter', 'twitter'
        PINTEREST = 'pinterest', 'pinterest'
        SNAPCHAT = 'snapchat', 'snapchat'
        TIKTOK = 'tiktok', 'tiktok'
        DISCORD = 'discord', 'discord'
        GITHUB = 'github', 'github'
 
class Profile(models.Model):   
        user = models.OneToOneField(CustomUser,  on_delete=models.CASCADE, related_name='profile') 
        image = StdImageField('Image', upload_to='profile', variations={'thumb': (500, 500, True)}, delete_orphans = True, blank=True)  
        occupation = models.CharField(max_length=120)
        description = models.TextField()  
        gender = models.CharField(max_length=20, blank=True)
        phone = models.CharField(max_length=20, blank=True)
        city = models.CharField(max_length=20, blank=True)
        country = models.CharField(max_length=20, blank=True)
        likes = models.ManyToManyField(CustomUser, blank=True, related_name='profile_likes')

        def __str__(self):
                return f' Profile: {self.user.username}'

        class Meta:
                verbose_name = "Profile"
                verbose_name_plural = "Profiles"
        
        @receiver(post_save, sender=CustomUser)
        def create_profile(sender, **kwargs):
                if kwargs.get('created', False):
                        Profile.objects.create(user=kwargs['instance'])

class Network(models.Model):
        user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='network', blank=True, null=True)  
        name = models.CharField(max_length=10, choices=SocialNetwork.choices, blank=True, null=True) 
        url = models.URLField(blank=True, null=True)

        def __str__(self):
                return f'{self.user or ""}, {self.name}'
        
        class Meta:
                verbose_name = "Network"
                verbose_name_plural = "Networks"
                ordering = ['user']

        @receiver(post_save, sender=CustomUser)
        def create_network(sender, **kwargs):  
                if kwargs.get('created', False):    
                        for i in SocialNetwork:
                                print(i)
                                Network.objects.create(name=i, user=kwargs['instance']) 
         
                                
                                

       

profile/forms.py
from django import forms
from profile.models import Network, Profile


class NetworkForm(forms.ModelForm):
    class Meta:
        model = Network
        fields = '__all__'


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

profile/views.py
import re
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic.base import View
from django.views.generic.edit import CreateView
from accounts.forms import CustomUserCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from base.base_admin_permissions import BaseAdminUsersAd
from django.views.generic import TemplateView, DetailView, UpdateView, ListView
from profile.models import Network, Profile
from rest_framework import viewsets
from accounts.models import CustomUser
from post.models import Post


class ProfileView(DetailView):
    model = CustomUser
    template_name = "profile/profile.html"
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "profile"
    object = None

    def get_object(self, queryset=None):
        self.profile = self.model.objects.select_related('profile').prefetch_related(
            "posts").prefetch_related("network").get(user_name=self.kwargs.get(self.slug_url_kwarg))
        return self.profile

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        page = self.request.GET.get('page')
        title = request.GET.get('title')
        if title:
            context['page_obj'] = Paginator(Post.objects.all().filter(
                title__icontains=title, author=self.object, is_activate__exact=True), 6).get_page(page)
            print("resultado filtro !!!")
            print(context['page_obj'])
        else:
            context['page_obj'] = Paginator(Post.objects.all().filter(
                author=self.object, is_activate__exact=True), 6).get_page(page)
            print("Todos os filtros !!!")
        return self.render_to_response(context)


class ProfileEditView(UpdateView):
    model = Profile
    template_name = "config/edit-profile.html"
    context_object_name = "profile"
    object = None
    fields = "__all__"

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['network'] = Network.objects.filter(user=self.request.user)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        print(request.POST.get('first_name'))
        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.save()
        profile = user.profile
        profile.about = request.POST.get('about')
        profile.occupation = request.POST.get('occupation')
        profile.description = request.POST.get('description')
        if request.POST.get('gender') == "Homem":
            profile.gender = "Homem"
        else:
            profile.gender = "Mulher"
        profile.country = request.POST.get('country')
        profile.city = request.POST.get('city')
        profile.phone = request.POST.get('phone')
        profile.save()
        # Ele junta duas listas, de preferencia do mesmo tamanho.
        networks = Network.objects.filter(user=self.request.user)
        urls = request.POST.getlist('url')
        for network, url in zip(networks, urls):
            network.url = url
            network.save()
        messages.success(self.request, 'Alterações salva com sucesso!!!')
        return redirect(reverse_lazy('profile:edit-profile'))


class EditPhotoProfile(UpdateView):
    model = Profile
    template_name = "profile/profile.html"
    template_name_suffix = '_update_form'
    fields = ['image']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(
            self.request, 'Imagem de profile atualizada com sucesso!!!')
        return reverse_lazy('profile:user-profile', args=[self.request.user.user_name])


class ProfileAddLike(LoginRequiredMixin, View):
    slug_field = "username"
    slug_url_kwarg = "username"

    def post(self, request, pk, *args, **kwargs):
        profile = Profile.objects.get(pk=pk)
        is_like = False
        for like in profile.likes.all():
            if like == request.user:
                is_like = True
                break
        if not is_like:
            profile.likes.add(request.user)

        if is_like:
            profile.likes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)


class ConfigView(TemplateView):
    template_name = "config/_config.html"


class UserListView(BaseAdminUsersAd, ListView):
    model = Profile
    template_name = 'config/usuarios.html'
    context_object_name = 'profile_list'

    def get_queryset(self):
        user_name = self.request.GET.get('user_name')
        is_active = self.request.GET.get('is_active')

        if user_name:
            profile_list = Profile.objects.filter(
                user__user_name__icontains=user_name)
            return profile_list
        if is_active:
            profile_list = Profile.objects.filter(user__is_active=is_active)
            return profile_list
        else:
            profile_list = Profile.objects.filter()
        return profile_list


class UserCreateView(CreateView):
    model = CustomUser
    form_class = CustomUserCreateForm
    template_name = 'config/add-user.html'
    success_url = reverse_lazy('profile:users-profile')

profile/templates/profile/profile.html
{% extends 'base/_base_home.html' %} {% load widget_tweaks %} {% load static %}
{% block body_home %} {% if not profile.profile.user.is_active %}
<section class="container-sm py-5">
  <div class="bg-light p-4 lead">
    <div class="row">
      <div class="col-md-1">
        <span class="link-danger"><i class="fas fa-times fa-5x"></i></span>
      </div>
      <div class="col">
        <br />
        <h1>Profile Deactivated or Deleted from the system !!!</h1>
      </div>
    </div>
  </div>
</section>
{% else %}
<section class="container-box row bg-light">
  <div class="d-flex align-items-center">
    <div class="flex-shrink-0 p-5">
      {% if profile.profile.image %}
      <img
        id="preview"
        class="rounded mx-auto d-block"
        src="{{profile.profile.image.thumb.url}}"
        alt="{{profile.first_name}}"
        width="200"
      />
      {% else %}
      <img
        id="preview"
        class="rounded mx-auto d-block"
        src="{% static 'images/default.png' %}"
        alt="default"
        alt="foto de profile"
        height="200"
      />
      {% endif %} {% if profile == request.user and
      request.user.is_authenticated %}
      <form
        method="post"
        action="{% url 'profile:photo-profile' profile.pk %}"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <div class="custom-file">
          <label class="label-input-photo custom-file-label" for="image"
            ><i class="fas fa-edit"></i
          ></label>
          <input
            type="file"
            onchange="this.form.submit()"
            value="Update"
            class="custom-file-input form-control"
            id="image"
            name="image"
          />
        </div>
      </form>
      {% endif %}
    </div>

    <div class="flex-grow-1 ms-3">
      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex flex-row align-items-center">
          <h1>{{profile.first_name}} {{profile.last_name}}</h1>
        </div>
        <form
          method="POST"
          action="{% url 'profile:like-profile' profile.pk %}"
        >
          {% csrf_token %}
          <input type="hidden" name="next" value="{{request.path}}" />
          <button type="submit" class="btn">
            <i class="fas fa-heart fa-2x s-label"></i
            ><span class="h3 mx-2 s-label"
              >{{profile.profile.likes.all.count}}</span
            >
          </button>
        </form>
      </div>
      <p>Username: {{profile.user_name}}</p>
      <div class="title-container">
        <h5>About:</h5>
      </div>
      <p>{{ profile.profile.description }}</p>
      <div class="row">
        <div class="col-6">
          <h5>I work on: {{profile.profile.occupation}}</h5>
          <p>City: {{profile.profile.city}} {{profile.profile.country}}</p>
        </div>
        <div class="col-6">
          <h5>Social networks:</h5>
          {% for n in profile.network.all %} {% if n.url != '' and n.url !=
          'None' %}
          <a href="{{n.url}}" target="_blank" class="s-label"
            ><i class="fab fa-{{n.name}} mx-2"></i
          ></a>
          {% endif %} {% endfor %}
        </div>
      </div>
      <div class="row">
        <div class="col py-2">
          <div class="d-flex justify-content-between align-items-center">
            <div class="d-flex flex-row align-items-center">
              <span>in join: {{profile.date_joined}}</span>
            </div>
            {% if profile == request.user and request.user.is_authenticated %}
            <button
              class="btn-default btn-red"
              onclick="location.href='http://127.0.0.1:8000/profile/edit-profile'"
            >
              <i class="fas fa-cog mx-2"></i>Edit profile
            </button>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<hr />
<section class="row">
  <div class="container-box col-md-3 p-3 bg-light">
    <h2>Perguntas</h2>
    <span class="fw-bold py-3">Title: </span>
    <form
      action="{% url 'profile:user-profile' profile.profile.user.user_name %}"
      method="get"
    >
      <input
        name="title"
        type="text"
        value="{{request.GET.title}}"
        class="form-control"
        placeholder="Search..."
      />
    </form>
    <br />
    {% if profile == request.user and request.user.is_authenticated %}
    <a href="{%  url 'profile:config' %}"
      ><button class="btn-default btn-red" type="button">
        Configurações
      </button></a
    >
    {% endif %} {% if request.GET.title %}
    <a href="{%  url 'profile:user-profile' profile.profile.user.user_name %}"
      ><button class="btn-default btn-red" type="button">Reset</button></a
    >
    {% endif %}
  </div>
  <div class="col-md-9">
    {% for post in page_obj %}
    <div class="container-box mt-2">
      <div class="d-flex justify-content-end align-items-center">
        {% if profile == request.user and request.user.is_authenticated %}
        <a class="s-label" href="{%  url 'post-update' post.pk %}"
          ><i class="fas fa-cog fa-2x mx-2"></i
        ></a>
        {% endif %}
      </div>
      {% include 'post/_card.html' %}
    </div>
    {% endfor %}
    <div class="p-4">
      {% if page_obj.paginator.num_pages > 1 %} {% include 'base/_page.html' %}
      {% endif %}
    </div>
  </div>
</section>
{% endif %}
<script>
  $('#image').change(function (event) {
    readURL(this)
  })
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader()
      var filename = $('#image').val()
      filename = filename.substring(filename.lastIndexOf('\\') + 1)
      reader.onload = function (e) {
        debugger
        $('#preview').attr('src', e.target.result)
        $('#preview').hide()
        $('#preview').fadeIn(500)
        $('.custom-file-label').text(filename)
      }
      reader.readAsDataURL(input.files[0])
    }
  }
</script>
{% endblock %}