accounts/urls.py
from django.urls import path, include 
from django.contrib.auth.views import PasswordResetDoneView
from accounts.views import UserLogin, UserCreate, UserChange, PasswordChange, PasswordReset, PasswordResetConfirm, PasswordResetComplete, UserDelete, TimeOutView 


app_name = "accounts"
urlpatterns = [
	path('login/', UserLogin.as_view(), name='login'),
	path('user-new/', UserCreate.as_view(), name='user-new'), 
	path('<int:pk>/update/', UserChange.as_view(), name='user-change'), 
	path('password-change/', PasswordChange.as_view(), name='password-change'),
        path('<int:pk>/delete/', UserDelete.as_view(), name='user-delete'),
	path('password-reset/', PasswordReset.as_view(), name='password-reset'),
	path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name="password_reset_confirm"),
	path('reset/done/', PasswordResetComplete.as_view(), name='password_reset_complete'),
	path('', include('django.contrib.auth.urls')), 
	path('timeout/', TimeOutView.as_view(), name='timeout'),
]
 

home/urls.py
from django.urls import path
from home.views import (CategoryFilterView, HomeView, DetailView, TagIndexView)
from home.likes_comments import (AddDislike, AddLike, CommentDeleteView, CommentEditView, CommentReplyView, AddCommentDislike, AddCommentLike) 

app_name = "home"
urlpatterns = [
        path('', HomeView.as_view(), name='home'),
        path('post-detail/<int:pk>/', DetailView.as_view(), name='post-detail'),
        path('tags/<slug:tag_slug>/', TagIndexView.as_view(), name='tagged'),
        path('category/<int:cat_slug>/', CategoryFilterView.as_view(), name='category'),
        path('post/<int:pk>/like', AddLike.as_view(), name='like'),
        path('post/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
        path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name="comment-delete"),
        path('post/<int:post_pk>/comment/edit/<int:pk>/', CommentEditView.as_view(), name="comment-edit"),
        path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name="comment-like"),
        path('post/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name="comment-dislike"),
        path('post/<int:post_pk>/comment/<int:pk>/reply', CommentReplyView.as_view(), name='comment-reply'),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('profile/', include('profile.urls')),
    path('post/', include('post.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/forms.py
from django import forms
from post.models import Post, SocialComment
 
class SocialPostForm(forms.ModelForm):
        body = forms.CharField(widget=forms.Textarea(attrs={'rows': '4','placeholder': 'Comentar alguma coisa...'}),required=True) 
        class Meta:
                model=Post
                fields=['body']


class SocialCommentForm(forms.ModelForm):
        comment = forms.CharField(widget=forms.Textarea(attrs={'rows': '2','placeholder': 'Responder comentário...'}),required=True)

        class Meta:
                model=SocialComment
                fields=['comment'] 

home/views.py
from typing import ContextManager
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from taggit.models import Tag
from post.models import Post, Category, SocialComment
from post.forms import PostForm
from home.forms import SocialCommentForm 


class HomeView(ListView):
        model = Post
        template_name = 'home/home.html'
        paginate_by = 5
       
        def get_queryset(self):
                title = self.request.GET.get('title')
                if title:
                        post_list = self.model.objects.filter(title__icontains=title, author__is_active__exact=True) 
                else:
                        post_list = self.model.objects.filter(author__is_active__exact=True) 
                return post_list

        def get_context_data(self, **kwargs): 
                context = super(HomeView, self).get_context_data(**kwargs)   
                context['form'] = PostForm() 
                context['category'] = Category.objects.all()
                context['tags'] = Tag.objects.all()
                return context


class DetailView(DetailView):
        model = Post
        template_name = 'home/post_detail.html'

        def get(self, request, pk, *args, **kwargs):
                post = Post.objects.get(pk=pk) 
                form = SocialCommentForm()
                comments = SocialComment.objects.filter(post=post).order_by('-created_on')
                post_list = self.model.objects.filter(author__is_active__exact=True)[:5]
                cat = Category.objects.all()
                tags = Tag.objects.all()
                
                # contador de visualização do post
                post_object = self.model.objects.get(pk=pk)
                post_object.views = post_object.views+1
                post_object.save() 
                
                context = {
                        'post': post, 
                        'form': form,
                        'comments': comments,
                        'post_list': post_list,
                        'cat': cat,
                        'tags': tags,
                }

                return render(request, 'home/post_detail.html', context)

        def post(self, request, pk, *args, **kwargs):
                        post = Post.objects.get(pk=pk)
                        form = SocialCommentForm(request.POST) 
                        cat = Category.objects.all()
                        tags = Tag.objects.all()

                        if form.is_valid():
                                new_comment = form.save(commit=False)
                                new_comment.author = request.user
                                new_comment.post = post
                                new_comment.save() 
                                
                        comments = SocialComment.objects.filter(post=post).order_by('-created_on')

                        context = {
                                'post': post,
                                'form': form,
                                'comments': comments,
                                'cat': cat,
                                'tags': tags,
                        }

                        return render(request, 'home/post_detail.html', context)


class TagIndexView(ListView):
        model = Post
        template_name = 'home/home.html'

        def get_context_data(self, **kwargs):
                context = super().get_context_data(**kwargs)
                context['tags'] = Tag.objects.all()
                return context

        def get_queryset(self):
                return Post.objects.filter(tags__slug=self.kwargs['tag_slug'])


class CategoryFilterView(ListView):
        model = Post
        template_name = 'home/home.html'

        def get_queryset(self):
                return Post.objects.filter(category__pk=self.kwargs['cat_slug'], author__is_active__exact=True)

home/templates/home/details/center.html
{% load static %}
<div class="container-box">
  <h4>{{post.title}}</h4>
  <div class="d-flex justify-content-between">
    <div class="d-flex flex-row">
      <small
        >Category:
        <span class="badge btn-success">{{post.category.name}}</span></small
      >
    </div>
    <span class="text-muted">{{post.published_date}}</span>
  </div>
  <div class="mt-3">
    <p>{{post.desc}}</p>
  </div>
  {% if post.files1.url != '' and post.files1.url != 'None' %}
  <a
    class="link-light bg-secondary p-1 mx-1 rounded"
    href="{{post.files1.url}}"
    target="_blank"
    ><i class="fas fa-link"></i
  ></a>
  {% endif %} {% if post.files2.url != '' and post.files2.url != 'None' %}
  <a
    class="link-light bg-secondary p-1 mx-1 rounded"
    href="{{post.files2.url}}"
    target="_blank"
    ><i class="fas fa-link"></i
  ></a>
  {% endif %} {% if post.files3.url != '' and post.files3.url != 'None' %}
  <a
    class="link-light bg-secondary p-1 mx-1 rounded"
    href="{{post.files3.url}}"
    target="_blank"
    ><i class="fas fa-link"></i
  ></a>
  {% endif %}
  <div class="d-flex justify-content-between align-items-center">
    <div class="d-flex flex-row">
      {% for tag in post.tags.all %}
      <a href="{% url 'home:tagged' tag.slug %}"
        ><span class="badge btn-gray mx-1">{{tag.name}}</span></a
      >
      {% endfor %}
    </div>
    <div class="d-flex flex-row align-items-center">
      <form
        method="POST"
        action="{% url 'home:like' post.pk %}"
        class="mt-2 px-2"
      >
        {% csrf_token %}
        <input type="hidden" name="next" value="{{request.path}}" />
        <button type="submit" class="btn link-danger">
          <i class="fas fa-heart"></i><span> {{post.likes.all.count}}</span>
        </button>
      </form>
      <form
        method="POST"
        action="{% url 'home:dislike' post.pk %}"
        class="mt-2 px-2"
      >
        {% csrf_token %}
        <input type="hidden" name="next" value="{{request.path}}" />
        <button type="submit" class="btn link-danger">
          <i class="fas fa-heart-broken"></i
          ><span> {{post.dislikes.all.count}}</span>
        </button>
      </form>
      <a
        class="link-dark"
        href="http://127.0.0.1:8000/profile/{{post.author.user_name}}"
      >
        {% if post.author.profile.image %}
        <img
          src="{{  post.author.profile.image.url }}"
          alt="{{ post.author.first_name }}"
          class="img-fluid rounded-circle"
          style="width: 40px; height: 40px; margin-right: 10px"
        />
        {% else %}
        <img
          src="{% static 'images/default.png' %}"
          class="img-fluid rounded-circle"
          alt="default"
          style="width: 40px; height: 40px; margin-right: 10px"
        />
        {% endif %}
      </a>
      <a
        class="link-dark"
        href="http://127.0.0.1:8000/profile/{{post.author.user_name}}"
      >
        {{ post.author.user_name}}
      </a>
    </div>
  </div>
</div>

home/templates/home/details/comments.html
{% load static %} {% if user.is_active %}
<form method="POST">
  {% csrf_token %}
  <textarea
    rows="3"
    name="comment"
    id="comment"
    placeholder="comentar..."
  ></textarea>
  <div class="mt-2">
    <button type="submit" class="btn-default btn-red">Responder</button>
  </div>
</form>
{% else %}
<div class="p-2 bg-light shadow-sm rounded">
  <div class="h4">Hello,</div>
  <p>You need to log in to the system to comment.</p>
  <button
    class="btn-default btn-red"
    onclick="location.href='{% url 'accounts:login' %}'"
  >
    <i class="fas fa-sign-in-alt"></i> Register/Login
  </button>
</div>
{% endif %}
<!-- COMMENT -->
<!-- COMMENT -->
<!-- COMMENT -->
<div class="p-4">
  <h4>Comments</h4>
  {% for comment in comments %} {% if comment.is_parent %}
  <div class="bg-light mt-3 p-3">
    <div class="d-flex justify-content-between align-items-center">
      <div class="d-flex flex-row align-items-center">
        {% if comment.author.profile.image %}
        <a href="http://127.0.0.1:8000/profile/{{comment.author.user_name}}">
          <img
            src="{{ comment.author.profile.image.url }}"
            width="30"
            height="30"
            class="rounded-circle mr-2"
          />
          {% else %}
          <img
            src="{% static 'images/default.png' %}"
            width="30"
            height="30"
            class="rounded-circle mr-2"
          />
          {% endif %}
        </a>
        <a href="http://127.0.0.1:8000/profile/{{comment.author.user_name}}">
          <small class="text-dark px-3"
            ><b>{{comment.author.user_name}}</b></small
          >
        </a>
      </div>
      <small class="fst-italic">{{comment.created_on}}</small>
    </div>
    <div class="justify-content-between mt-2 align-items-center px-4">
      <p class="text-dark text-break lh-sm px-4">{{comment.comment}}</p>
    </div>
    <div class="d-flex justify-content-between align-items-center">
      <div class="d-flex flex-row align-items-center mt-2 px-4">
        {% if request.user == comment.author %}
        <a
          href="{% url 'home:comment-edit' post.pk comment.pk %}"
          class="link-secondary"
        >
          <i class="fas fa-edit mx-2"></i
        ></a>
        <a
          href="{% url 'home:comment-delete' post.pk comment.pk %}"
          class="link-secondary"
        >
          <i class="fas fa-trash"></i>
        </a>
        {% endif %} {% if user.is_active %}
        <button
          class="btn btn-light link-danger p-2 rounded-lg"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapse_{{comment.id}}"
          aria-expanded="false"
          aria-controls="collapseExample"
        >
          <i class="fa fa-reply"></i>Responder
        </button>
        {% endif %}
      </div>
      <div class="d-flex flex-row align-items-center">
        <form
          method="POST"
          action="{% url 'home:comment-like' post.pk comment.pk %}"
        >
          {% csrf_token %}
          <input type="hidden" name="next" value="{{request.path}}" />
          <button type="submit" class="btn btn-light link-danger">
            <i class="fas fa-heart"></i><span>{{comment.likes.all.count}}</span>
          </button>
        </form>
        <form
          method="POST"
          action="{% url 'home:comment-dislike' post.pk comment.pk %}"
        >
          {% csrf_token %}
          <input type="hidden" name="next" value="{{request.path}}" />
          <button type="submit" class="btn btn-light link-danger">
            <i class="fas fa-heart-broken"></i
            ><span>{{comment.dislikes.all.count}}</span>
          </button>
        </form>
      </div>
    </div>
  </div>
  <div class="collapse bg-light mt-1" id="collapse_{{comment.id}}">
    <form
      method="POST"
      action="{% url 'home:comment-reply' post.pk comment.pk %}"
    >
      {% csrf_token %} {{form.comment}}
      <div class="d-flex justify-content-between align-items-center py-2">
        <button type="submit" class="btn-default btn-red">Enviar</button>
        <button
          class="p-2 btn-default btn-red"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapse_{{comment.id}}"
          aria-expanded="false"
          aria-controls="collapseExample"
        >
          <i class="fas fa-times"></i>
        </button>
      </div>
    </form>
  </div>
  <!-- REPLY COMMENT -->
  <!-- REPLY COMMENT -->
  <!-- REPLY COMMENT -->
  <div class="ms-5">
    {% for child_comment in comment.children %}
    <div class="bg-light mt-3 p-3">
      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex flex-row align-items-center">
          {% if child_comment.author.profile.image %}
          <img
            src="{{ child_comment.author.profile.image.url }}"
            width="30"
            height="30"
            height="30"
            class="rounded-circle mr-2"
          />
          {% else %}
          <img
            src="{% static 'images/default.png' %}"
            width="30"
            height="30"
            class="rounded-circle mr-2"
          />
          {% endif %}
          <small class="text-dark px-3"
            ><b>{{child_comment.author.user_name}}</b></small
          >
        </div>
        <small class="fst-italic">{{child_comment.created_on}}</small>
      </div>
      <div class="justify-content-between mt-2 align-items-center px-4">
        <p class="text-dark text-break lh-sm px-4">{{child_comment.comment}}</p>
      </div>
      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex flex-row align-items-center mt-2 px-4">
          {% if request.user == child_comment.author %}
          <a
            href="{% url 'home:comment-edit' post.pk child_comment.pk %}"
            class="link-secondary"
          >
            <i class="fas fa-edit mx-2"></i
          ></a>
          <a
            href="{% url 'home:comment-delete' post.pk child_comment.pk %}"
            class="link-secondary"
          >
            <i class="fas fa-trash"></i>
          </a>
          {% endif %}
        </div>
        <div class="d-flex flex-row">
          <form
            method="POST"
            action="{% url 'home:comment-like' post.pk child_comment.pk %}"
          >
            {% csrf_token %}
            <input type="hidden" name="next" value="{{request.path}}" />
            <button type="submit" class="btn btn-light link-danger">
              <i class="fas fa-heart"></i
              ><span>{{child_comment.likes.all.count}}</span>
            </button>
          </form>
          <form
            method="POST"
            action="{% url 'home:comment-dislike' post.pk child_comment.pk %}"
          >
            {% csrf_token %}
            <input type="hidden" name="next" value="{{request.path}}" />
            <button type="submit" class="btn btn-light link-danger">
              <i class="fas fa-heart-broken"></i
              ><span>{{child_comment.dislikes.all.count}}</span>
            </button>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %} {% endfor %}
</div>

home/templates/home/details/right.html
{% load widget_tweaks %} {% load static %}
<div class="container-box">
  <h6>All Tags</h6>
  <form class="d-flex" method="GET">
    <div class="form-group col">
      {% for tag in tags %}
      <a href="{% url 'home:tagged' tag.slug %}"
        ><span class="btn-tags btn-gray">{{tag.name}}</span></a
      >
      {% endfor %}
    </div>
  </form>
</div>