accounts/urls.py
from django.urls import path, include 
from django.contrib.auth.views import PasswordResetDoneView
from accounts.views import UserLogin, UserCreate, UserChange, PasswordChange, PasswordReset, PasswordResetConfirm, PasswordResetComplete, UserDelete, TimeOutView 


app_name = "accounts"
urlpatterns = [
	path('login/', UserLogin.as_view(), name='login'),
	path('user-new/', UserCreate.as_view(), name='user-new'), 
	path('<int:pk>/update/', UserChange.as_view(), name='user-change'), 
	path('password-change/', PasswordChange.as_view(), name='password-change'),
        path('<int:pk>/delete/', UserDelete.as_view(), name='user-delete'),
	path('password-reset/', PasswordReset.as_view(), name='password-reset'),
	path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name="password_reset_confirm"),
	path('reset/done/', PasswordResetComplete.as_view(), name='password_reset_complete'),
	path('', include('django.contrib.auth.urls')), 
	path('timeout/', TimeOutView.as_view(), name='timeout'),
]
 

home/urls.py
from django.urls import path
from home.views import (CategoryFilterView, HomeView, DetailView, TagIndexView)
from home.likes_comments import (AddDislike, AddLike, CommentDeleteView, CommentEditView, CommentReplyView, AddCommentDislike, AddCommentLike) 

app_name = "home"
urlpatterns = [
        path('', HomeView.as_view(), name='home'),
        path('post-detail/<int:pk>/', DetailView.as_view(), name='post-detail'),
        path('tags/<slug:tag_slug>/', TagIndexView.as_view(), name='tagged'),
        path('category/<int:cat_slug>/', CategoryFilterView.as_view(), name='category'),
        path('post/<int:pk>/like', AddLike.as_view(), name='like'),
        path('post/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
        path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name="comment-delete"),
        path('post/<int:post_pk>/comment/edit/<int:pk>/', CommentEditView.as_view(), name="comment-edit"),
        path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name="comment-like"),
        path('post/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name="comment-dislike"),
        path('post/<int:post_pk>/comment/<int:pk>/reply', CommentReplyView.as_view(), name='comment-reply'),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    path('profile/', include('profile.urls')),
    path('post/', include('post.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path
from profile.views import ProfileAddLike, EditPhotoProfile, ProfileView, ProfileEditView, UserListView, UserCreateView, ConfigView

app_name = "profile"
urlpatterns = [
    path('config/', ConfigView.as_view(), name="config"),
    path('edit-profile', ProfileEditView.as_view(), name="edit-profile"),
    path('<slug:username>', ProfileView.as_view(), name="user-profile"),
    path('profile/<int:pk>/like', ProfileAddLike.as_view(), name='like-profile'),
    path('<int:pk>/photo/', EditPhotoProfile.as_view(), name='photo-profile'),
    path('usuarios/', UserListView.as_view(), name='users-profile'),
    path('usernew/', UserCreateView.as_view(), name='usernew'),
]

base/templates/base/_base_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
        <title>{% block title %}{% endblock %}</title>
        {% include 'base/_head.html' %}
</head>

<body> 
        {% include 'base/_navbar.html' %}
        <div class="container py-5">
        {% include 'base/_messages.html' %}
        {% block body_home %}
        {% endblock %}
        </div>
</body>
<script>
        setTimeout(function () {
                if ($('#msg').length > 0) {
                        $('#msg').remove();
                }
        }, 2000)
</script>
</html>

base/templates/base/_footer.html
<div class="mt-5 pt-5 pb-5 shadow">
    <div class="container">
        <div class="row"> 
            <div class="col text-center">
                <p>Instagram: @eticialima</p><p class="mb-0"><i class="fa fa-phone mr-3"></i> 16 994256485</p>
                <p class=""><small>© 2022. Todos os Direitos Reservados.</small></p>
            </div> 
        </div> 
    </div>
</div>

base/templates/base/_head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"> 
<meta http-equiv="X-UA-Compatible" content="ie=edge">
 
<!-- CSS local --> 
<link rel="stylesheet" href="{% static 'css/style.css' %}">   

<!-- Bootstrap CSS --> 
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>  
 
<!-- Fontawesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

<!-- Script local -->
<link rel="stylesheet" href="/static/css/tagsinput.css" /> 
<script src="/static/js/tagsinput.js"></script>
<script src="/static/js/scripts.js"></script>

base/templates/base/_messages.html
{% if messages %} 
{% for message in messages %}
<div class="alert {{ message.tags }}" id="msg" role="alert">{{ message }}</div>
{% endfor %} {% endif %} {% if form.non_field_errors %}
<div class="alert alert-danger" id="msg" role="alert">{{ form.non_field_errors }}</div>
{% endif %} {% if form.errors %}
<div class="alert alert-danger" id="msg" role="alert">{{ form.errors }}</div>
{% endif %}  

base/templates/base/_navbar.html
{% load static %}
<header>
        <div id="brand"><a href="/">ForumXYZ</a></div> 
        <nav>
                <ul>
                        <li>
                                <form class="d-flex" method="get" action="{% url 'home:home' %}"> 
                                        <input class="search" type="text" name="title" id="title" placeholder="Search...">
                                </form>
                        </li>
                        <li><a href="/">Start</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Contact</a></li> 
                        <li><button class=" btn-default btn-red d-flex" onclick="location.href='{% url 'post-create' %}'"><i class="fa fa-plus mx-2"></i> Ask a Question</button></li>
                        <li>

                                {% if user.is_authenticated %} 
                                <div class="action">
                                        <div class="profile" onclick="menuToggle();">
                                                {% if user.profile.image %}
                                                <div class="circle-home">
                                                        <img src="{{ user.profile.image.url }}" class="img-fluid" alt="{{ user.first_name }}" />
                                                </div>
                                                {% else %}
                                                <div class="circle-home">
                                                        <img src="{% static 'images/default.png' %}" class="img-fluid" alt="default" />
                                                </div>
                                                {% endif %}
                                        </div>

                                        <div class="menu text-start lh-lg"> 
                                                <a href="{% url 'profile:user-profile' user.user_name %}" class="link-secondary">Meu profile</a> 
                                                <a href="{% url 'profile:config' %}" class="link-secondary">Configurações</a> 
                                                <button class=" btn-default btn-red d-flex" onclick="location.href='{% url 'accounts:logout' %}'">Logout</button> 
                                        </div>
                                </div>
                                {% else %}
                                        <button class=" btn-default btn-red d-flex" onclick="location.href='{% url 'accounts:login' %}'">Login</button> 
                                {% endif %}

                        </li>
                </ul>
        </nav>

        <div id="navbar-icon" onclick="toggleMobileMenu(this)">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
                <ul class="mobile-menu">
                        <li><a href="/">Start</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Contact</a></li> 
                        <br>

                        {% if user.is_authenticated %} 
                        <li><a href="#">{{ user.user_name }}</a></li> 
                        <li><a href="{% url 'profile:user-profile' user.user_name %}">Meu profile</a></li> 
                        <li><a href="{% url 'profile:config' %}">Settings</a></li>
                        <li><button class=" btn-default btn-red d-flex" onclick="location.href='{% url 'accounts:logout' %}'">Logout</button></li> 
                        {% else %} 
                        <button class=" btn-default btn-red d-flex" onclick="location.href='{% url 'accounts:login' %}'">Login</button></li>
                        {% endif %} 

                </ul>
        </div>
</header>
<script>
        function toggleMobileMenu(menu) {
                menu.classList.toggle('open');
        } 
        function menuToggle() {
                const toggleMenu = document.querySelector('.menu');
                toggleMenu.classList.toggle('active')
        }
</script>

<style> 
        header {
                background-color: rgb(17, 50, 77);
                height: 100px;
                display: flex;
                justify-content: space-evenly;
                align-content: space-around;
                flex-wrap: nowrap;
                flex-direction: row;
                align-items: stretch;
        }

        header a {
                text-decoration: none;
        }


        #brand {
                font-weight: bold;
                font-size: 18px;
                display: flex;
                align-items: center;
        }

        #brand a {
                color: #fdfdfd;
        }

        ul {
                list-style: none; 
                height: 100%;
                display: flex;
                align-items: center;
                justify-content: space-around;
        }

        ul a {
                color: white; 
                font-size: 17px;
                padding: 7px 13px;
                border-radius: 3px;
                text-decoration: none;
        }

        ul li {
                padding: 5px;
                margin-left: 10px;
        }
  
        ul li a:hover { 
                color: rgb(215, 127, 161); 
                text-decoration: none;
        }


        #navbar-icon {
                margin: auto 0;
                display: none;
                cursor: pointer;
        }

        #navbar-icon div {
                width: 35px;
                height: 3px;
                background-color: white;
                margin: 6px 0;
                transition: 0.4s;
        }

        .open .bar1 {
                -webkit-transform: rotate(-45deg) translate(-6px, 6px);
                transform: rotate(-45deg) translate(-6px, 6px);
        }

        .open .bar2 {
                opacity: 0;
        }

        .open .bar3 {
                -webkit-transform: rotate(45deg) translate(-6px, -8px);
                transform: rotate(45deg) translate(-6px, -8px);
        }

        .open .mobile-menu {
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: flex-start;
                background-color: #11324D;
                ;
        }

        .mobile-menu {
                display: none;
                position: absolute;
                top: 100px;
                left: 0;
                height: calc(100vh - 50px);
                width: 100%;
        }

        .mobile-menu li {
                margin-bottom: 10px;
        }

        .logo {
                color: #393939;
                justify-self: start;
                margin-left: 20px;
                cursor: pointer;
                text-decoration: none;
                font-size: 2rem;
                display: flex;
                align-items: center;
        }

        .logo:hover {
                color: rgb(215, 127, 161);
                text-decoration: none;
        }

        .circle-home {
                border-radius: 50%;
                width: 50px;
                height: 50px;
                overflow: hidden;
                position: relative;
                margin-inline: auto;
        }

        .action {
                position: fixed;
                top: 20px;
        }

        .action .profile {
                border-radius: 50%;
                cursor: pointer;
                height: 60px;
                overflow: hidden;
                position: relative;
                width: 60px;
        }

        .action .profile img {
                width: 100%;
                top: 0;
                position: absolute;
                object-fit: cover;
                left: 0;
                height: 100%;
        }

        .action .menu {
                background-color: #FFF;
                box-shadow: rgb(111 111 111 / 20%) 0px 0px 8px 0px;
                border-radius: 20px;
                padding: 25px 40px;
                position: relative;
                width: 200px;
                transition: 0.5s;
                top: 0px;
                right: 130px;
                visibility: hidden;
                opacity: 0;
        }

        .action .menu.active {
                opacity: 1;
                top: 0px;
                right: 130px;
                visibility: visible;
        }

        .action .menu::before {
                background-color: #fff;
                content: '';
                height: 20px;
                position: absolute;
                right: 30px;
                transform: rotate(45deg);
                top: -5px;
                width: 20px;
        }

        @media only screen and (max-width: 600px) {
                header nav {
                        display: none;
                }

                #navbar-icon {
                        display: block;
                }
        }
</style>

base/templates/base/_page.html
{% if page_obj.has_previous %}
{% if request.GET.title %}
<a class="pagination-action link" href="?page=1&title={{request.GET.title}}">
        <i class="fa fa-angle-double-left link-secundary" aria-hidden="true"></i>
</a>
<a class="pagination-action" href="?page={{ page_obj.previous_page_number }}&title={{request.GET.title}}">
        <i class="fa fa-angle-left link-secundary" aria-hidden="true"></i>
</a>
{% else %}
<a class="pagination-action" href="?page=1">
        <i class="fa fa-angle-double-left link-secundary" aria-hidden="true"></i>
</a>
<a class="pagination-action" href="?page={{ page_obj.previous_page_number }}">
        <i class="fa fa-angle-left link-secundary" aria-hidden="true"></i>
</a>
{% endif %}
{% endif %}
{% for num in page_obj.paginator.page_range %}
{% if request.GET.title %}
{% if page_obj.number == num %}
<span class="pagination-number pagination-current">{{ num }}</span>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}<a class="pagination-number link-light" href="?page={{ num }}&title={{request.GET.title}}">{{ num }}</a>
{% endif %}
{% else %}
{% if page_obj.number == num %}
<span class="pagination-number pagination-current">{{ num }}</span>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}<a class="pagination-number link-light" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endif %}
{% endfor %}
{% if page_obj.has_next %}
{% if request.GET.title %}
<a class="pagination-action" href="?page={{ page_obj.next_page_number }}&title={{request.GET.title}}">
        <i class="fa fa-angle-right link-secundary" aria-hidden="true"></i>
</a>
<a class="pagination-action"
        href="?page={{ page_obj.paginator.num_pages }}&title={{request.GET.title}}">
        <i class="fa fa-angle-double-right link-secundary" aria-hidden="true"></i>
</a>
{% else %}
<a class="pagination-action" href="?page={{ page_obj.next_page_number }}">
        <i class="fa fa-angle-right link-secundary" aria-hidden="true"></i>
</a>
<a class="pagination-action" href="?page={{ page_obj.paginator.num_pages }}">
        <i class="fa fa-angle-double-right link-secundary" aria-hidden="true"></i>
</a>
{% endif %}
{% endif %}